### ISSUE TITLE
建议添加 gemini-pro 自定义 endpoint

### ISSUE THREAD

**Issue by sherlcok314159** [pot-app/pot-desktop#702]
### Description

默认的 gemini-pro 请求速度很慢，建议支持添加自定义的地址

### Application Scenario

因为 gemini-pro 很慢，同时可以用 vercel 自定义部署

**Comment by iG8R** [comment]
Yes, please, add a customizable `requestPath` for `GeminiPro` as is done in `OpenAI`, because in some countries GeminiPro doesn't work due to geo-restrictions from Google, but there are proxies, e.g. https://github.com/antergone/palm-netlify-proxy , that get around this issue.
And, please, add also the Ukrainian language to [src/services/translate/geminipro/info.ts](https://github.com/pot-app/pot-desktop/commit/4a0d2549907888f59cd4f9f2de270b150ef1847e#diff-14e86c507ce33abab1114f38e74eff4663487ef19c684cc3cef7c8828d4dc264)

<img src="https://github.com/pot-app/pot-desktop/assets/11407417/a2e6fe10-00f0-4d53-8495-98f4db7afa56" width="350">

**Comment by Pylogmon** [comment]
Okay, I'll add it later

**Comment by Pylogmon** [comment]
You can later download the latest version installation package compiled by Actions [here](https://github.com/pot-app/pot-desktop/actions/runs/8020223879)

**Comment by iG8R** [comment]
@Pylogmon 
Thanks a lot!

Please, add also the Ukrainian language to src/services/translate/geminipro/info.ts

**Comment by iG8R** [comment]
Works like a charm, although it needs to enter the full request path, e.g. `xxx.netlify.app/v1beta/models/gemini-pro` , but that is even better, since the user can input whichever version (v1 or v1beta) and model (gemini or gemini-pro) they want.
